version: '3.8'
services:
  linux:
    build:
      context: cobalt/docker/linux
      cache_from:
        - ghcr.io/youtube/cobalt_sandbox/linux:latest
    image: ghcr.io/youtube/cobalt_sandbox/linux:latest
    platform: linux/amd64
    environment:
      - DEPOT_TOOLS_UPDATE=0
  unittest:
    build:
      context: cobalt/docker/unittest
      cache_from:
        - ghcr.io/youtube/cobalt_sandbox/unittest:latest
    image: ghcr.io/youtube/cobalt_sandbox/unittest:latest
  webtest:
    build:
      context: cobalt/docker/webtest
      cache_from:
        - ghcr.io/youtube/cobalt_sandbox/webtest:latest
    image: ghcr.io/youtube/cobalt_sandbox/webtest:latest
